# Disable sudo to speed up build
sudo: false

# Python version
language: python
python:
  - "3.6"

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Run scripts
script:
  - coverage run test_politico.py

# After success run
after_success:
  - coveralls
